// demo/react/Post.jsx
import React from 'react';

export default function Post(props) {
  const { name, avatar, likesCount, image, text, date, onAvatarClick } = props;

  return (
    <div className="demo-post">
      <div className="demo-post-header">
        <a href="#" className="demo-post-avatar" onClick={onAvatarClick}>
          <img src={avatar} />
        </a>
        <div className="demo-post-name">{name}</div>
        <button className="demo-post-header-actions">
          <span />
          <span />
          <span />
        </button>
      </div>
      <div className="demo-post-image">
        <img src={image} />
      </div>
      <div className="demo-post-footer">
        <div className="demo-post-footer-actions">
          <div className="demo-post-footer-actions-left">
            <button>
              <img src="icons/like.svg" />
            </button>
            <button>
              <img src="icons/comment.svg" />
            </button>
            <button>
              <img src="icons/send.svg" />
            </button>
          </div>
          <div className="demo-post-footer-actions-right">
            <button>
              <img src="icons/bookmark.svg" />
            </button>
          </div>
        </div>
        <div className="demo-post-likes">Likes: {likesCount}</div>
        <div className="demo-post-content">
          <span className="demo-post-content-name">{name}</span>
          <span className="demo-post-content-text">{text}</span>
        </div>
        <div className="demo-post-date">{date}</div>
      </div>
    </div>
  );
}

// demo/vue/Post.vue
<template>
  <div class="demo-post">
    <div class="demo-post-header">
      <a href="#" class="demo-post-avatar" @click="onAvatarClick">
        <img :src="avatar" />
      </a>
      <div class="demo-post-name">{{ name }}</div>
      <button class="demo-post-header-actions">
        <span />
        <span />
        <span />
      </button>
    </div>
    <div class="demo-post-image">
      <img :src="image" />
    </div>
    <div class="demo-post-footer">
      <div class="demo-post-footer-actions">
        <div class="demo-post-footer-actions-left">
          <button>
            <img src="icons/like.svg" />
          </button>
          <button>
            <img src="icons/comment.svg" />
          </button>
          <button>
            <img src="icons/send.svg" />
          </button>
        </div>
        <div class="demo-post-footer-actions-right">
          <button>
            <img src="icons/bookmark.svg" />
          </button>
        </div>
      </div>
      <div class="demo-post-likes">Likes: {{ likesCount }}</div>
      <div class="demo-post-content">
        <span class="demo-post-content-name">{{ name }}</span>
        <span class="demo-post-content-text">{{ text }}</span>
      </div>
      <div class="demo-post-date">{{ date }}</div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    name: {
      type: String,
      default: '',
    },
    avatar: {
      type: String,
      default: '',
    },
    likesCount: {
      type: [String, Number],
      default: '',
    },
    image: {
      type: String,
      default: '',
    },
    text: {
      type: String,
      default: '',
    },
    date: {
      type: String,
      default: '',
    },
  },
  emits: ['avatarClick'],
  setup(props, ctx) {
    const onAvatarClick = (e) => {
      ctx.emit('avatarClick', e);
    };

    return {
      onAvatarClick,
    };
  },
};
</script>
